electron/fiddle-core

package.json
src/installer.ts
src/runner.ts
src/versions.ts
yarn.lock

No API changes / no functional changes.
Most of this is bumping dependencies & devDependencies to be up-to-date. There are also a couple of small code cleanups, e.g. declaring an object `as const` and fixing a comment typo.

deps: update dependencies

---

src/installer.ts

Prev conversations - https://electronhq.slack.com/archives/C03G7RWF6KH/p1657217133597039!

refactor: properly handle removal of electron version

---

.github/workflows/ci.yml

This PR adds a GH Actions test run for PRs.

ci: add test runs to PRs

---

.github/workflows/ci.yml

ci: install dependencies with --frozen-lockfile flag

---

dist/fiddle-core.d.ts
src/index.ts
src/installer.ts
tests/installer.test.ts

Link to discussion - https://github.com/electron/fiddle/pull/1134#discussion_r952949487

feat: allow usage of already unzipped electron versions

---

.github/workflows/semantic.yml

chore: add semantic commit check

---

.github/workflows/semantic.yml

Fixes deprecation warnings on the action runs.

chore: bump version of semantic commit check action

---

README.md

docs: fix versions example in README

---

.github/workflows/lint.yml

build: add lint workflow

---

tests/versions.test.ts

Adds test coverage for `ElectronVersions`.

test: add tests for ElectronVersions

---

src/versions.ts
tests/versions.test.ts

fix: use stale cache in ElectronVersions if fetch fails

---

.github/workflows/docs.yml
api-extractor.json
package.json

Adds a CI workflow that will ensure `etc/fiddle-core.api.md` stays updated.

build: add docs workflow

---

.circleci/config.yml

In preparation of doing more PRs on this repo, expand the test matrix.

build: cleanup test workflow and expand test matrix

---

tests/runner.test.ts

Cleans up typings a bit and uses a temp file for the versions cache so that the tests aren't using the real versions cache on the system - ran into an issue where a different test I was working on truncated my versions cache and then these tests started failing because they were depending on that versions cache.

test: improve runner.test.ts

---

etc/fiddle-core.api.md
src/index.ts
src/versions.ts
tests/versions.test.ts

To fix downstream https://github.com/electron/fiddle/issues/1222.

feat: initialVersions option for ElectronVersions

---

src/installer.ts
tests/installer.test.ts

An error in `Installer.install(version)` currently leaves the installer in a bad state and the install can't be retried since it thinks it is currently in-progress. Seeing this in the Sentry errors for Fiddle.

fix: clear installing state on error

---

src/versions.ts
tests/versions.test.ts

fix: only 3 major versions are supported

---

src/installer.ts
tests/installer.test.ts

Seeing some downstream issues in Fiddle where the install state for a version gets stuck when an error happens while installing or downloading. This PR ensures we reset the install state on error.

fix: reset install state on error

---

src/installer.ts

These not being wrapped with `noAsar` causes problems in Electron Fiddle with E28 and above. Both call sites were also switched to using sync versions to avoid any unintended side effects from setting `noAsar`.
No tests unfortunately because this isn't something we can easily test.

fix: wrap filesystem removes with noAsar

---

etc/fiddle-core.api.md
package.json
yarn.lock

chore: bump Typescript to `5.6.3`

---

package.json
yarn.lock

build: update prettier and eslint-plugin-prettier
