electron/fiddle-core

src/versions.ts

While digging through the source code, I found that when processing `VersionsCache` File, If the file doesn't read or found the catch block handles nothing but instead it has a single comment.
I thought this is a great way to improve by handling with `debug` to address this while debugging.

chore: Wrote debug line in catch block instead of comment

---

src/runner.ts
tests/runner.test.ts

The `README` documents the usage of `Runner.create` as 
```js
const runner = await Runner.create();
```
which throws an error of object parameters being undefined [here](https://github.com/electron/fiddle-core/blob/e6e2808fedd81981bf4019ddc2711e3e4f905220/src/runner.ts#L56).
Fixed this by adding a default empty object parameter to the `Runner.create` method (which seems like the right way rather than `await Runner.create({})`.

refactor: add default parameter for Runner.create

---

README.md

The `.on` function emitter takes in an object parameter. Hence, deconstructed the values first :)

docs: fix the given API usage example

---

README.md
dist/fiddle-core.d.ts
src/installer.ts
tests/installer.test.ts

This commit essentially let users pass an additional parameter to Installer which are handles the downloading process of electron binary.
Basically, the user can now - 
* Pass an a callback function to `ensureDownloaded`/`install` function which is triggered when a binary is being downloaded.
* Downloading electron binary from custom sources by specifying the base mirror.
`progressCallback` - 
```ts
const callback = (progress: ProgressObject) => {
const percent = progress.percent * 100;
console.log(`Current download progress %: ${percent.toFixed(2)}`);
};
await installer.ensureDownloaded('12.0.15', {
progressCallback: callback,
});
```
`mirror` - 
```ts
const myMirror = {
electronMirror: '<base electron mirror>',
electronNightlyMirror: '<for nightly version>',
},
await …
```

feat: add installing options for electron binary

---

dist/fiddle-core.d.ts
src/installer.ts
tests/installer.test.ts

This only allows certain strings to be passed when dealing with version states.

refactor: modify InstallState to be an enum

---

src/installer.ts

This commit adds the support to allow installing of multiple electron version together.
Previously, there was a single global variable denoting the installing state of electron version. Hence, when a new version triggers the `install` function - it throws an error due to [this](https://github.com/electron/fiddle-core/blob/e22ae4d453ba21c5d40f47b153105f632a624c9a/src/installer.ts#L287) check.
With changing it to be `Map`, we can keep track to all version and their installing state :)

feat: allow installing of multiple version simultaneously

---

package.json
yarn.lock

The latest version of `get` fixes the checksum error in case of China proxies (https://github.com/electron/get/pull/226#issuecomment-1208824651) which is required here in order to ship https://github.com/electron/fiddle/pull/1134.

build(deps): upgrade @electron/get

---

package.json

`fiddle-core` has CLI functionality, as documented in `README`, but it's not actually exposed. This exposes it so that the examples in the CLI can be run verbatim.

feat: expose fiddle-core CLI from package

---

src/fiddle.ts

Closes https://github.com/electron/fiddle/issues/1198.
Refs https://github.com/electron/fiddle/pull/1134.
We need to do something similar to what's done here: https://github.com/electron/fiddle-core/blob/e6387a14ec5d97012a49d63f95e9c86aaf6d74c0/src/installer.ts#L348-L355 and https://github.com/electron/fiddle-core/blob/e6387a14ec5d97012a49d63f95e9c86aaf6d74c0/src/installer.ts#L361-L369 on the off chance that any of the dependencies in `node_modules` themselves bundle Electron.

fix: fiddle-core failing spawn on Electron deps

---

src/fiddle.ts

Linting error slipped in on #45 because looks like PRs stopped running the CircleCI job (being looked into).

chore: fix linting error

---

src/ambient.d.ts
src/fiddle.ts
src/installer.ts

Removes the need for @ts-ignore comments when used in code.

chore: add process.noAsar typing as ambient declaration

---

src/index.ts
src/installer.ts

This needs to be exported (see example in README) but isn't currently.

fix: export ProgressObject type

---

package.json
yarn.lock

This shouldn't impact consumers at all as the `simple-git` upgrade is transparent given we weren't using removed methods

fix: update deps to clean up yarn audit

---

README.md

Examples in the docs didn't get updated for the new package name.

docs: update package name

---

package.json

Will fix the package on npm having a not useful description.

build: add description to package.json

---

src/installer.ts
tests/installer.test.ts

Currently, if the zip files for a version get deleted after `Installer` is instantiated, it can't recover and won't re-download the zip. Seeing this error in the Sentry errors for Fiddle.

fix: re-download zip file if it is missing

---

etc/fiddle-core.api.md
src/versions.ts
tests/versions.test.ts

Can be useful to easily ignore the cache so that `ElectronVersions` can be used to fetch the latest versions on create.

feat: option to ignore cache in ElectronVersions.create

---

package.json
src/installer.ts
tests/installer.test.ts
yarn.lock

`rimraf` has retry logic on Windows which should fix various errors being seen in downstream Fiddle.

fix: use rimraf to remove current version directory

---

.github/workflows/docs.yml
.github/workflows/lint.yml

Bumps versions to get things off EOL Node.js versions and preempts deprecation warnings.

ci: update workflows

---

src/versions.ts
tests/versions.test.ts

It's unexpected to silently get an `ElectronVersions` object with no populated versions on fetch failures. This fix also properly handles the case where the server returns a non-200 response, which is currently processed as if it was a normal response.

fix: don't return empty ElectronVersions on fetch failures

---

.github/workflows/semantic.yml

Noticed this wasn't pinned like we do on other repos.

ci: pin action-semantic-pull-request version
